### ISSUE TITLE
-i option does not work

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/cffsubr#7]
I always get:

```
Traceback (most recent call last):
  File "/python3.7/site-packages/cffsubr/__main__.py", line 64, in <module>
    main()
  File "/python3.7/site-packages/cffsubr/__main__.py", line 60, in main
    font.save(options.output_file)
  File "/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 163, in save
    "Can't overwrite TTFont when 'lazy' attribute is True")
fontTools.ttLib.TTLibError: Can't overwrite TTFont when 'lazy' attribute is True
```

**Comment by anthrotype** [comment]
Thanks for the report. I fixed it with https://github.com/adobe-type-tools/cffsubr/commit/e4d05f80a95202ac420c74c8e344ff005b34fbb3

I'll make a bugfix release shortly

**Comment by khaledhosny** [comment]
Thanks!
